version: '3.8'

services:
  # PostgreSQL database service for Spring Boot and Superset
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: library_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Solr service for search capabilities
  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command: 
      - solr-precreate
      - gettingstarted
    networks:
      - app-network
    
networks:
  app-network:

volumes:
  db_data:
  solr_data:
